import { NextRequest,NextResponse } from "next/server";
import { createAppointmentWorkflow,getAppointmentWorkflowLookups,listAppointmentWorkflow } from "@/lib/appointment-workflow-db";
import { getCurrentSession } from "@/lib/session";
export const runtime="nodejs"; export const dynamic="force-dynamic";
async function auth(){const session=await getCurrentSession();if(!session)return{session:null,response:NextResponse.json({message:"نشست شما منقضی شده است؛ دوباره وارد شوید."},{status:401})};if(!session.permissions.appointments&&!session.isSystemAdmin)return{session:null,response:NextResponse.json({message:"مجوز دسترسی به فرایند انتصابات را ندارید."},{status:403})};return{session,response:null};}
function id(value:FormDataEntryValue|null){const n=Number(value);return Number.isSafeInteger(n)&&n>0?n:0;}
function message(error:unknown){return error instanceof Error&&error.message?error.message:"انجام عملیات انتصابات با خطا روبه‌رو شد.";}
export async function GET(request:NextRequest){const a=await auth();if(!a.session)return a.response;try{if(request.nextUrl.searchParams.get("mode")==="lookups"){const search=(request.nextUrl.searchParams.get("search")||"").trim().slice(0,150);return NextResponse.json(await getAppointmentWorkflowLookups(a.session.userId,search));}return NextResponse.json({rows:await listAppointmentWorkflow(a.session.userId)});}catch(error){console.error("Appointment workflow GET failed",error);return NextResponse.json({message:message(error)},{status:500});}}
export async function POST(request:NextRequest){const a=await auth();if(!a.session)return a.response;try{const form=await request.formData();const personId=id(form.get("personId")),postId=id(form.get("postId"));if(!personId||!postId)return NextResponse.json({message:"شخص و پست پیشنهادی را انتخاب کنید."},{status:400});
  let reasons:unknown,initialInterview:unknown;try{reasons=JSON.parse(String(form.get("reasons")||"[]"));initialInterview=JSON.parse(String(form.get("initialInterview")||"{}"));}catch{return NextResponse.json({message:"اطلاعات فرم معتبر نیست."},{status:400});}
  if(!Array.isArray(reasons))return NextResponse.json({message:"حداقل یک دلیل وارد کنید."},{status:400});const clean=reasons.filter(x=>typeof x==="string"&&x.trim()).map(x=>String(x).trim().slice(0,1000)).slice(0,10);if(!clean.length)return NextResponse.json({message:"حداقل یک دلیل وارد کنید."},{status:400});
  const file=form.get("proposalImage");if(!(file instanceof File))return NextResponse.json({message:"تصویر نامه پیشنهاد انتصاب تولید نشد."},{status:400});if(file.type!=="image/png"||file.size>12*1024*1024)return NextResponse.json({message:"فایل نامه باید PNG و حداکثر ۱۲ مگابایت باشد."},{status:400});
  const result=await createAppointmentWorkflow({actorUserId:a.session.userId,personId,postId,reasons:clean,initialInterview,fileName:file.name.slice(0,150),contentType:file.type,fileData:Buffer.from(await file.arrayBuffer())});return NextResponse.json({message:"پیشنهاد انتصاب ثبت و به کارتابل بررسی ارسال شد.",...result},{status:201});
 }catch(error){console.error("Appointment workflow create failed",error);return NextResponse.json({message:message(error)},{status:500});}}
