"use client";
import { SearchableDropdown, type DropdownOption } from "@/component/Dropdown";
import domtoimage from "dom-to-image";
import styles from "./Workflow.module.css";

export type InterviewAnswers={familiarity:string;verbal:string;expression:string;writing:string;appearance:string;physical:string;beliefNotes:string;managementNotes:string;strengths:string;concerns:string;result:string};
export const emptyInterview:InterviewAnswers={familiarity:"",verbal:"",expression:"",writing:"",appearance:"",physical:"",beliefNotes:"",managementNotes:"",strengths:"",concerns:"",result:""};
const options=[{key:"familiarity",label:"میزان شناخت قبلی",items:["خیلی زیاد","زیاد","معمولی","کم","بدون شناخت"]},{key:"verbal",label:"توان فهم و استماع کلامی",items:["توانمند","معمولی","کم‌توان"]},{key:"expression",label:"فن بیان مناسب و شفاف",items:["توانمند","معمولی","کم‌توان"]},{key:"writing",label:"توانمندی نوشتاری و گزارش‌نویسی",items:["توانمند","معمولی","کم‌توان"]},{key:"appearance",label:"آراستگی ظاهری",items:["مناسب","معمولی","نامناسب"]},{key:"physical",label:"توانمندی جسمی",items:["توانمند","معمولی","کم‌توان"]}] as const;
const resultOptions:DropdownOption<string>[]=["پیشنهاد می‌شود","نیازمند بررسی بیشتر","پیشنهاد نمی‌شود"].map(item=>({value:item,label:item}));
const searchableDropdownProps={
  placeholder:"انتخاب کنید",
  searchPlaceholder:"جست‌وجوی گزینه...",
  emptyText:"گزینه‌ای برای نمایش وجود ندارد.",
  noResultText:"گزینه‌ای پیدا نشد.",
  compact:true,
  menuWidth:320,
};
export function InterviewEditor({value,onChange,readOnly=false,title="فرم مصاحبه"}:{value:InterviewAnswers;onChange:(v:InterviewAnswers)=>void;readOnly?:boolean;title?:string}){return <section className={styles.interviewBox}><h3>{title}</h3><div className={styles.interviewGrid}>{options.map(q=><label key={q.key}><span>{q.label}</span><SearchableDropdown<string> {...searchableDropdownProps} disabled={readOnly} value={value[q.key]||null} options={q.items.map(item=>({value:item,label:item}))} onChange={next=>onChange({...value,[q.key]:next})} className={styles.workflowDropdown} menuClassName={styles.workflowDropdownMenu}/></label>)}</div><div className={styles.notesGrid}><label>ویژگی‌های اعتقادی و اخلاقی<textarea disabled={readOnly} value={value.beliefNotes} onChange={e=>onChange({...value,beliefNotes:e.target.value})}/></label><label>توان مدیریتی و سازماندهی<textarea disabled={readOnly} value={value.managementNotes} onChange={e=>onChange({...value,managementNotes:e.target.value})}/></label><label>نقاط قوت<textarea disabled={readOnly} value={value.strengths} onChange={e=>onChange({...value,strengths:e.target.value})}/></label><label>موارد قابل بررسی<textarea disabled={readOnly} value={value.concerns} onChange={e=>onChange({...value,concerns:e.target.value})}/></label></div><label className={styles.resultField}>جمع‌بندی مصاحبه<SearchableDropdown<string> {...searchableDropdownProps} disabled={readOnly} value={value.result||null} options={resultOptions} onChange={result=>onChange({...value,result})} className={styles.workflowDropdown} menuClassName={styles.workflowDropdownMenu}/></label></section>}

export type LetterData={fullName:string;fatherName:string;codeMelli:string;birthDate:string;postTitle:string;requesterName:string;requesterPost:string;recipientName:string;recipientPost:string;reasons:string[];date?:string};
export function ProposalLetterCard({id,data}:{id:string;data:LetterData}){return <div id={id} className={styles.a4} dir="rtl"><div className={styles.letterDate}>{data.date||new Date().toLocaleDateString("fa-IR")}</div><h2>پیشنهاد انتصاب</h2><div className={styles.recipient}>جناب آقای {data.recipientName||"................"}<br/>{data.recipientPost||"مقام محترم بررسی‌کننده انتصابات"}</div><p>با سلام و احترام؛</p><p>مطابق با شیوه‌نامه اجرایی آیین‌نامه انتصابات، آقای <em>{data.fullName||"................"}</em> فرزند <em>{data.fatherName||"................"}</em> با کد ملی <em>{data.codeMelli||"................"}</em> و تاریخ تولد <em>{data.birthDate||"................"}</em> جهت تصدی مسئولیت <em>{data.postTitle||"................"}</em> پیشنهاد می‌گردد. خواهشمند است دستور فرمایید بررسی و اقدام لازم انجام شود.</p><h3>دلایل و ویژگی‌های اجمالی فرد پیشنهادی:</h3><ol>{data.reasons.filter(Boolean).map((x,i)=><li key={`${i}-${x}`}>{x}</li>)}</ol><div className={styles.letterSign}><span>{data.requesterName||"................"}</span><span>{data.requesterPost||"................"}</span></div></div>}
export function AppointmentOrderCard({id,data,tarikh,duration}:{id:string;data:LetterData;tarikh:string;duration:number}){return <div id={id} className={`${styles.a4} ${styles.orderA4}`} dir="rtl"><div className={styles.letterDate}>تاریخ: {tarikh||"................"}</div><h2>حکم انتصاب مسئولیت</h2><div className={styles.recipient}>جناب آقای {data.fullName||"................"}</div><p>سلام علیکم؛</p><p>با عنایت به تعهد، شایستگی و سوابق جنابعالی، به موجب این حکم از تاریخ <em>{tarikh||"................"}</em> به مدت <em>{duration?duration.toLocaleString("fa-IR"):"...."} ماه</em> به عنوان <em>{data.postTitle||"................"}</em> منصوب می‌شوید.</p><p>امید است با اتکال به خداوند متعال و در چارچوب قوانین و ضوابط، در انجام وظایف محوله و تحقق اهداف سازمان موفق باشید.</p><div className={styles.orderHighlights}><span>نام و نام خانوادگی</span><strong>{data.fullName||"—"}</strong><span>کد ملی</span><strong>{data.codeMelli||"—"}</strong><span>عنوان مسئولیت</span><strong>{data.postTitle||"—"}</strong><span>مدت ابلاغ</span><strong>{duration?`${duration.toLocaleString("fa-IR")} ماه`:"—"}</strong></div><div className={styles.letterSign}><span>{data.recipientName||"................"}</span><span>{data.recipientPost||"مقام تأییدکننده"}</span></div></div>}
async function dataUrlToFile(dataUrl:string,fileName:string){const res=await fetch(dataUrl);const blob=await res.blob();return new File([blob],fileName,{type:blob.type||"image/png"});}
export async function exportA4(id:string,fileName:string){const node=document.getElementById(id);if(!node)return null;await document.fonts?.ready;const width=794,height=1123,scale=2;const dataUrl=await domtoimage.toPng(node,{width:width*scale,height:height*scale,style:{transform:`scale(${scale})`,transformOrigin:"top left",width:`${width}px`,height:`${height}px`,minWidth:`${width}px`,minHeight:`${height}px`,maxWidth:`${width}px`,maxHeight:`${height}px`,margin:"0",boxShadow:"none",overflow:"hidden"},bgcolor:"#fff"});return dataUrlToFile(dataUrl,fileName);}
