"use client";
import {useEffect,useMemo,useState} from "react";
import {emptyInterview,exportA4,InterviewEditor,ProposalLetterCard,type InterviewAnswers,type LetterData} from "./AppointmentForms";
import styles from "./Workflow.module.css";
type Person={PersonId:number;CodeMelli:string;FullName:string;FatherName:string;TarikhTavalod:string|null;Shoghl:string|null;TelHamrah:string|null};
type Post={PostId:number;PostOnvan:string};type Context={RequesterFullName:string|null;RequesterPostTitle:string|null;DestinationFullName:string|null;DestinationPostTitle:string|null};
export default function NewAppointmentModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const[persons,setPersons]=useState<Person[]>([]),[posts,setPosts]=useState<Post[]>([]),[context,setContext]=useState<Context|null>(null),[search,setSearch]=useState(""),[postSearch,setPostSearch]=useState(""),[personId,setPersonId]=useState(0),[postId,setPostId]=useState(0),[reasons,setReasons]=useState([""]),[interview,setInterview]=useState<InterviewAnswers>(emptyInterview),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const timer=window.setTimeout(async()=>{setLoading(true);try{const r=await fetch(`/api/appointments/workflow?mode=lookups&search=${encodeURIComponent(search)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message);setPersons(d.persons||[]);setPosts(d.posts||[]);setContext(d.context||null);}catch(e){setError(e instanceof Error?e.message:"دریافت اطلاعات انجام نشد.");}finally{setLoading(false);}},search?300:0);return()=>clearTimeout(timer);},[search]);
 const person=persons.find(x=>x.PersonId===personId)||null,post=posts.find(x=>x.PostId===postId)||null;const cleanReasons=reasons.map(x=>x.trim()).filter(Boolean);const data:LetterData={fullName:person?.FullName||"",fatherName:person?.FatherName||"",codeMelli:person?.CodeMelli||"",birthDate:person?.TarikhTavalod||"",postTitle:post?.PostOnvan||"",requesterName:context?.RequesterFullName||"",requesterPost:context?.RequesterPostTitle||"",recipientName:context?.DestinationFullName||"",recipientPost:context?.DestinationPostTitle||"",reasons:cleanReasons};
 const filteredPosts=useMemo(()=>posts.filter(x=>x.PostOnvan.toLocaleLowerCase("fa").includes(postSearch.trim().toLocaleLowerCase("fa"))),[postSearch,posts]);
 const submit=async()=>{if(!person||!post){setError("شخص و پست پیشنهادی را انتخاب کنید.");return;}if(!cleanReasons.length){setError("حداقل یک دلیل وارد کنید.");return;}if(!interview.result){setError("جمع‌بندی مصاحبه اولیه را انتخاب کنید.");return;}setSaving(true);setError("");try{const image=await exportA4("appointment-proposal-letter-new",`appointment-proposal-${person.CodeMelli}.png`);if(!image)throw new Error("تولید تصویر نامه انجام نشد.");const form=new FormData();form.append("personId",String(person.PersonId));form.append("postId",String(post.PostId));form.append("reasons",JSON.stringify(cleanReasons));form.append("initialInterview",JSON.stringify(interview));form.append("proposalImage",image);const r=await fetch("/api/appointments/workflow",{method:"POST",body:form});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"ثبت درخواست انجام نشد.");onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:"ثبت درخواست انجام نشد.");}finally{setSaving(false);}};
 return <div className={styles.fullModal} dir="rtl"><header className={styles.modalHeader}><div><span>انتصابات / درخواست جدید</span><h2>پیشنهاد انتصاب جدید</h2></div><button onClick={onClose} disabled={saving}>×</button></header><div className={styles.newModalBody}><aside className={styles.formPanel}><div className={styles.panelScroll}><section className={styles.formSection}><h3>انتخاب فرد و مسئولیت</h3><label>جست‌وجوی شخص<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="نام، نام خانوادگی یا کد ملی..."/></label><label>فرد پیشنهادی<select value={personId} onChange={e=>setPersonId(Number(e.target.value))}><option value={0}>{loading?"در حال دریافت...":"انتخاب شخص"}</option>{persons.map(x=><option value={x.PersonId} key={x.PersonId}>{x.FullName} — {x.CodeMelli}</option>)}</select></label><label>جست‌وجوی پست<input value={postSearch} onChange={e=>setPostSearch(e.target.value)} placeholder="عنوان پست..."/></label><label>پست پیشنهادی<select value={postId} onChange={e=>setPostId(Number(e.target.value))}><option value={0}>انتخاب پست خالی</option>{filteredPosts.map(x=><option value={x.PostId} key={x.PostId}>{x.PostOnvan}</option>)}</select></label>{person?<div className={styles.personSummary}><strong>{person.FullName}</strong><span>کد ملی: {person.CodeMelli}</span><span>شغل: {person.Shoghl||"—"}</span><span>تلفن: {person.TelHamrah||"—"}</span></div>:null}</section><section className={styles.formSection}><div className={styles.sectionTitle}><h3>دلایل پیشنهاد</h3>{reasons.length<10?<button type="button" onClick={()=>setReasons(x=>[...x,""])}>+ افزودن</button>:null}</div>{reasons.map((x,i)=><div className={styles.reasonInput} key={i}><span>{(i+1).toLocaleString("fa-IR")}</span><textarea value={x} onChange={e=>setReasons(r=>r.map((v,j)=>j===i?e.target.value.slice(0,1000):v))} placeholder="دلیل و ویژگی فرد پیشنهادی..."/><button type="button" onClick={()=>setReasons(r=>r.length===1?[""]:r.filter((_,j)=>j!==i))}>×</button></div>)}</section><InterviewEditor value={interview} onChange={setInterview} title="مصاحبه اولیه"/></div><footer className={styles.panelFooter}>{error?<span className={styles.inlineError}>{error}</span>:null}<button className={styles.secondaryButton} onClick={onClose}>بستن</button><button className={styles.primaryButton} onClick={()=>void submit()} disabled={saving}>{saving?"در حال ثبت...":"ثبت و ارسال پیشنهاد"}</button></footer></aside><main className={styles.previewPanel}><span className={styles.previewLabel}>پیش‌نمایش نامه A4</span><div className={styles.paperStage}><ProposalLetterCard id="appointment-proposal-letter-new" data={data}/></div></main></div></div>}
