import { NextRequest,NextResponse } from "next/server";
import { decideAppointmentWorkflow } from "@/lib/appointment-workflow-db";
import { getCurrentSession, sessionHasMenu } from "@/lib/session";
import { ACCESS_MENU } from "@/lib/access-menu";
export const runtime="nodejs";export const dynamic="force-dynamic";type C={params:Promise<{entesabId:string}>};
export async function POST(request:NextRequest,c:C){const session=await getCurrentSession();if(!session)return NextResponse.json({message:"نشست شما منقضی شده است."},{status:401});if(!sessionHasMenu(session, ACCESS_MENU.appointmentsWorkflow))return NextResponse.json({message:"مجوز بررسی درخواست را ندارید."},{status:403});const entesabId=Number((await c.params).entesabId);if(!Number.isSafeInteger(entesabId)||entesabId<1)return NextResponse.json({message:"شناسه درخواست معتبر نیست."},{status:400});
 try{const form=await request.formData();const action=String(form.get("action")||"") as "save-interview"|"approve"|"reject";if(!["save-interview","approve","reject"].includes(action))return NextResponse.json({message:"عملیات معتبر نیست."},{status:400});let finalInterview:unknown=null;if(action!=="reject"){try{finalInterview=JSON.parse(String(form.get("finalInterview")||"{}"));}catch{return NextResponse.json({message:"فرم مصاحبه نهایی معتبر نیست."},{status:400});}}
 const note=String(form.get("note")||"").trim().slice(0,1000)||null;const date=String(form.get("tarikhEblagh")||"").trim().slice(0,20)||null;const months=Number(form.get("durationMonths")||0)||null;const file=form.get("orderImage");const orderFile=file instanceof File?file:null;if(action==="approve"&&(!orderFile||orderFile.type!=="image/png"||orderFile.size>12*1024*1024))return NextResponse.json({message:"تصویر حکم انتصاب تولید نشد یا معتبر نیست."},{status:400});
 const result=await decideAppointmentWorkflow({actorUserId:session.userId,entesabId,action,finalInterview,note,tarikhEblagh:date,durationMonths:months,fileName:orderFile?.name.slice(0,150)??null,contentType:orderFile?.type??null,fileData:orderFile?Buffer.from(await orderFile.arrayBuffer()):null});return NextResponse.json({message:action==="approve"?"پیشنهاد تأیید و حکم انتصاب صادر شد.":action==="reject"?"پیشنهاد انتصاب تأیید نشد.":"مصاحبه نهایی ذخیره شد.",...result});
 }catch(error){console.error("Appointment workflow action failed",error);return NextResponse.json({message:error instanceof Error?error.message:"ثبت نتیجه بررسی انجام نشد."},{status:500});}}
